-- Run this once in the Supabase SQL Editor for an existing project.
-- This is additive and does not change or delete existing items or transactions.
create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  contact text default '',
  created_at timestamptz default now()
);

create index if not exists idx_vendors_name on public.vendors(name);

notify pgrst, 'reload schema';