create table if not exists public.items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  supplier_name text default 'General Supplier',
  supplier_contact text default '',
  quantity integer not null default 0,
  unit_price numeric(12,2) not null default 0,
  total_value numeric(14,2) not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  type text not null,
  transaction_time timestamptz default now(),
  item_id bigint references public.items(id) on delete set null,
  item_name text,
  supplier_name text,
  customer_name text,
  reference_no text,
  quantity integer default 0,
  unit_price numeric(12,2) default 0,
  total_amount numeric(14,2) default 0,
  reason_code text,
  notes text default ''
);

-- Upgrade existing installations from the previous size/color schema.
alter table public.items add column if not exists quantity integer not null default 0;
alter table public.items add column if not exists unit_price numeric(12,2) not null default 0;
alter table public.items add column if not exists total_value numeric(14,2) not null default 0;

alter table public.transactions add column if not exists transaction_time timestamptz default now();
alter table public.transactions add column if not exists unit_price numeric(12,2) default 0;
alter table public.transactions add column if not exists total_amount numeric(14,2) default 0;

-- Preserve existing transaction dates when upgrading from the old timestamp column.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'transactions'
      and column_name = 'timestamp'
  ) then
    update public.transactions
    set transaction_time = "timestamp"
    where "timestamp" is not null;
  end if;
end $$;

create index if not exists idx_transactions_transaction_time on public.transactions(transaction_time desc);
create index if not exists idx_items_supplier_name on public.items(supplier_name);

notify pgrst, 'reload schema';
