create table if not exists public.items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  supplier_name text default 'General Supplier',
  supplier_contact text default '',
  quantity integer not null default 0,
  unit_price numeric(12,2) not null default 0,
  total_value numeric(14,2) not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  type text not null,
  transaction_time timestamptz default now(),
  item_id bigint references public.items(id) on delete set null,
  item_name text,
  supplier_name text,
  customer_name text,
  reference_no text,
  quantity integer default 0,
  unit_price numeric(12,2) default 0,
  total_amount numeric(14,2) default 0,
  reason_code text,
  description text default '',
  notes text default ''
);

create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  contact text default '',
  created_at timestamptz default now()
);

-- Upgrade existing installations from the previous size/color schema.
alter table public.items add column if not exists quantity integer not null default 0;
alter table public.items add column if not exists unit_price numeric(12,2) not null default 0;
alter table public.items add column if not exists total_value numeric(14,2) not null default 0;

alter table public.transactions add column if not exists transaction_time timestamptz default now();
alter table public.transactions add column if not exists unit_price numeric(12,2) default 0;
alter table public.transactions add column if not exists total_amount numeric(14,2) default 0;
alter table public.transactions add column if not exists description text default '';

-- Preserve existing transaction dates when upgrading from the old timestamp column.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'transactions'
      and column_name = 'timestamp'
  ) then
    update public.transactions
    set transaction_time = "timestamp"
    where "timestamp" is not null;
  end if;
end $$;

create index if not exists idx_transactions_transaction_time on public.transactions(transaction_time desc);
create index if not exists idx_items_supplier_name on public.items(supplier_name);
create index if not exists idx_vendors_name on public.vendors(name);

alter table public.vendors enable row level security;
grant usage, select on sequence public.vendors_id_seq to anon, authenticated;
grant select, insert, update, delete on table public.vendors to anon, authenticated;

drop policy if exists "Browser users can read vendors" on public.vendors;
create policy "Browser users can read vendors" on public.vendors for select to anon, authenticated using (true);
drop policy if exists "Browser users can add vendors" on public.vendors;
create policy "Browser users can add vendors" on public.vendors for insert to anon, authenticated with check (true);
drop policy if exists "Browser users can update vendors" on public.vendors;
create policy "Browser users can update vendors" on public.vendors for update to anon, authenticated using (true) with check (true);
drop policy if exists "Browser users can delete vendors" on public.vendors;
create policy "Browser users can delete vendors" on public.vendors for delete to anon, authenticated using (true);

notify pgrst, 'reload schema';
