create table if not exists public.items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  supplier_name text default 'General Supplier',
  supplier_contact text default '',
  unit_cost numeric(12,2) default 0,
  wholesale_price numeric(12,2) default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.variants (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.items(id) on delete cascade,
  size text not null default '',
  color text not null default '',
  stock_quantity integer not null default 0,
  unique(item_id, size, color)
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  type text not null,
  timestamp timestamptz default now(),
  item_id bigint references public.items(id) on delete set null,
  item_name text,
  supplier_name text,
  customer_name text,
  reference_no text,
  size text,
  color text,
  quantity integer default 0,
  unit_cost numeric(12,2) default 0,
  wholesale_price numeric(12,2) default 0,
  reason_code text,
  total_cost_amount numeric(12,2) default 0,
  total_wholesale_amount numeric(12,2) default 0,
  notes text default ''
);

create index if not exists idx_variants_item_id on public.variants(item_id);
create index if not exists idx_transactions_timestamp on public.transactions(timestamp desc);
create index if not exists idx_items_supplier_name on public.items(supplier_name);
